### PR TITLE
feat: add leather request header

### PR DESCRIPTION
**Pull request by alter-eggo**
All Hiro requests in the app are made using stacks js library, so we can intercept requests to pass request header in such a way

### CODE REVIEW

**Comment by kyranjamie** [comment]
I see here you're overriding the actually browser `fetch` method. I thought that the stacks packages offer a way to pass in a fetch fn. 

https://github.com/hirosystems/stacks.js/blob/2cf886b6419232dbb54caccf5216b4f42605f3ad/packages/stacking/src/index.ts#L347-L349

Instead, can't we pass in a new `fetch`, similar to the one you've created here, via `client` object and apply the header that way?

**Comment by kyranjamie** [comment]
Isn't that something we kind of need to do anyway?

I think this really boils down to whether we're looking to make a quick fix, or actually invest in Lockstacks henceforth cc/ @markmhendrickson

**Comment by markmhendrickson** [comment]
@kyranjamie does this PR work as intended and your suggestion is to improve overall code quality, or is it needed for it functionally to work?

@alter-eggo what's your general estimate on how much work his suggestion would take?

**Comment by kyranjamie** [comment]
I think we should do it, we can make sure to do a full QA

**Comment by alter-eggo** [comment]
this was added here https://github.com/leather-io/lockstacks/pull/200

**Pull request closed without merging**
