### PR TITLE
Change type of balance to bigint

### PR DESCRIPTION
**Pull request by friedger**
This PR
* changes the check for stx balance type from string to bigint, the new type returned from the api

### CODE REVIEW

**Review by hstove — APPROVED** [review]

**Comment by friedger** [comment]
How can we avoid these type of errors in the future?

**Comment by markmhendrickson** [comment]
@alter-eggo @kyranjamie @camerow let's get this merged and released 🙏

**Comment by markmhendrickson** [comment]
@friedger do we know when this bug was introduced?

**Comment by friedger** [comment]
When the hiro api node was updated

**Comment by friedger** [comment]
With stacks.js 7.0
https://github.com/hirosystems/stacks.js/commit/8ce84a38822d9c1d26e8e2cc63f0c627d9c9e165#diff-ccdb0bb6da8b004bd30e4096246ea81c8114afbb3c85daa96efe691f881cb5feR390

**Comment by friedger** [comment]
4 days ago: https://github.com/leather-io/lockstacks/commit/2a90cc00daf93ab91e246e94ccc5bb8a7ab94889

**Comment by camerow** [comment]
> How can we avoid these type of errors in the future?

If this code was unit tested we would have found these issues. I've been doing a ton of UI work in this project but as I have I think we could do a lot to make this project more "mature" and production ready (analytics, tests, documentation, etc)

**Pull request merged**
